apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  # 저장용량
  capacity:
    storage: 1Gi
  # block / file system
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    # 이 볼륨이 단일노드에 의해 읽기/쓰기 볼륨으로 마운트 될 수 있음
    - ReadWriteOnce
    # 읽기전용, 여러 노드에서 요청할 수 있음 (hostPath에서 지원안함)
    # - ReadOnlyMany
    # 읽기쓰기가 가능, 여러 노드에서 요청할 수 있음 (hostPath에서 지원안함)
    # - ReadWriteMany
  # 현재 미니큐브환경에서 단일노드로 작동하므로, hostPath 사용
  # 테스트 환경에서는, 노드에 대한 독립성이 보장되지 않음
  # 그러나 다양한 프로바이더용 저장소를 이용하면, pod과 노드에 독립적인
  # 영구볼륨을 만들 수 있음
  hostPath:
    path: /data
    type: DirectoryOrCreate
